// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dailyRequestCounts = `-- name: DailyRequestCounts :many
SELECT day, SUM(used)::int4 AS total
FROM daily_usage
WHERE day >= CURRENT_DATE - INTERVAL '29 days'
GROUP BY day
ORDER BY day ASC
`

type DailyRequestCountsRow struct {
	Day   pgtype.Date
	Total int32
}

func (q *Queries) DailyRequestCounts(ctx context.Context) ([]DailyRequestCountsRow, error) {
	rows, err := q.db.Query(ctx, dailyRequestCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyRequestCountsRow
	for rows.Next() {
		var i DailyRequestCountsRow
		if err := rows.Scan(&i.Day, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersAdmin = `-- name: ListUsersAdmin :many
SELECT u.id, u.email, u.role, u.banned, u.created_at, u.daily_quota_override,
       COALESCE(SUM(du.used), 0)::int4 AS requests_today
FROM users u
LEFT JOIN ado_keys k ON k.user_id = u.id
LEFT JOIN daily_usage du ON du.key_id = k.id AND du.day = CURRENT_DATE
GROUP BY u.id
ORDER BY u.created_at DESC
`

type ListUsersAdminRow struct {
	ID                 uuid.UUID
	Email              string
	Role               string
	Banned             bool
	CreatedAt          pgtype.Timestamptz
	DailyQuotaOverride *int32
	RequestsToday      int32
}

func (q *Queries) ListUsersAdmin(ctx context.Context) ([]ListUsersAdminRow, error) {
	rows, err := q.db.Query(ctx, listUsersAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersAdminRow
	for rows.Next() {
		var i ListUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.Banned,
			&i.CreatedAt,
			&i.DailyQuotaOverride,
			&i.RequestsToday,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserQuotaOverride = `-- name: RemoveUserQuotaOverride :exec
UPDATE users SET daily_quota_override = NULL, updated_at = NOW() WHERE id = $1
`

func (q *Queries) RemoveUserQuotaOverride(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeUserQuotaOverride, id)
	return err
}

const setUserQuotaOverride = `-- name: SetUserQuotaOverride :exec
UPDATE users SET daily_quota_override = $2, updated_at = NOW() WHERE id = $1
`

type SetUserQuotaOverrideParams struct {
	ID                 uuid.UUID
	DailyQuotaOverride *int32
}

func (q *Queries) SetUserQuotaOverride(ctx context.Context, arg SetUserQuotaOverrideParams) error {
	_, err := q.db.Exec(ctx, setUserQuotaOverride, arg.ID, arg.DailyQuotaOverride)
	return err
}

const setUserRole = `-- name: SetUserRole :exec
UPDATE users SET role = $2, updated_at = NOW() WHERE id = $1
`

type SetUserRoleParams struct {
	ID   uuid.UUID
	Role string
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) error {
	_, err := q.db.Exec(ctx, setUserRole, arg.ID, arg.Role)
	return err
}

const topUsersByUsageThisMonth = `-- name: TopUsersByUsageThisMonth :many
SELECT u.email, COALESCE(SUM(du.used), 0)::int4 AS total
FROM users u
LEFT JOIN ado_keys k ON k.user_id = u.id
LEFT JOIN daily_usage du ON du.key_id = k.id
  AND du.day >= DATE_TRUNC('month', CURRENT_DATE)
GROUP BY u.id, u.email
ORDER BY total DESC
LIMIT 10
`

type TopUsersByUsageThisMonthRow struct {
	Email string
	Total int32
}

func (q *Queries) TopUsersByUsageThisMonth(ctx context.Context) ([]TopUsersByUsageThisMonthRow, error) {
	rows, err := q.db.Query(ctx, topUsersByUsageThisMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopUsersByUsageThisMonthRow
	for rows.Next() {
		var i TopUsersByUsageThisMonthRow
		if err := rows.Scan(&i.Email, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
