// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: error_logs.sql

package db

import (
	"context"
)

const countErrorLogs = `-- name: CountErrorLogs :one
SELECT COUNT(*) FROM error_logs
`

func (q *Queries) CountErrorLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countErrorLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteErrorLog = `-- name: DeleteErrorLog :exec
DELETE FROM error_logs WHERE id = $1
`

func (q *Queries) DeleteErrorLog(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteErrorLog, id)
	return err
}

const deleteOldErrorLogs = `-- name: DeleteOldErrorLogs :exec
DELETE FROM error_logs WHERE created_at < NOW() - INTERVAL '1 day' * $1
`

func (q *Queries) DeleteOldErrorLogs(ctx context.Context, dollar_1 interface{}) error {
	_, err := q.db.Exec(ctx, deleteOldErrorLogs, dollar_1)
	return err
}

const insertErrorLog = `-- name: InsertErrorLog :exec
INSERT INTO error_logs (level, message, context) VALUES ($1, $2, $3)
`

type InsertErrorLogParams struct {
	Level   string
	Message string
	Context []byte
}

func (q *Queries) InsertErrorLog(ctx context.Context, arg InsertErrorLogParams) error {
	_, err := q.db.Exec(ctx, insertErrorLog, arg.Level, arg.Message, arg.Context)
	return err
}

const listErrorLogs = `-- name: ListErrorLogs :many
SELECT id, level, message, context, created_at FROM error_logs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListErrorLogsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListErrorLogs(ctx context.Context, arg ListErrorLogsParams) ([]ErrorLog, error) {
	rows, err := q.db.Query(ctx, listErrorLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ErrorLog
	for rows.Next() {
		var i ErrorLog
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.Message,
			&i.Context,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
