// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keys.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAdoKey = `-- name: CreateAdoKey :one
INSERT INTO ado_keys (user_id, key_prefix, key_hash, daily_limit)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, key_prefix, key_hash, daily_limit, revoked_at, created_at, last_used_at
`

type CreateAdoKeyParams struct {
	UserID     uuid.UUID
	KeyPrefix  string
	KeyHash    []byte
	DailyLimit int32
}

func (q *Queries) CreateAdoKey(ctx context.Context, arg CreateAdoKeyParams) (AdoKey, error) {
	row := q.db.QueryRow(ctx, createAdoKey,
		arg.UserID,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.DailyLimit,
	)
	var i AdoKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.DailyLimit,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getActiveKeyByHash = `-- name: GetActiveKeyByHash :one
SELECT k.id, k.user_id, k.reasoning_mode,
       COALESCE(u.daily_quota_override, k.daily_limit)::int4 AS daily_limit,
       u.banned
FROM ado_keys k
JOIN users u ON u.id = k.user_id
WHERE k.key_hash = $1 AND k.revoked_at IS NULL
`

type GetActiveKeyByHashRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ReasoningMode bool
	DailyLimit    int32
	Banned        bool
}

func (q *Queries) GetActiveKeyByHash(ctx context.Context, keyHash []byte) (GetActiveKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveKeyByHash, keyHash)
	var i GetActiveKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReasoningMode,
		&i.DailyLimit,
		&i.Banned,
	)
	return i, err
}

const getActiveKeyByUser = `-- name: GetActiveKeyByUser :one
SELECT id, user_id, key_prefix, key_hash, daily_limit, revoked_at, created_at, last_used_at FROM ado_keys WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) GetActiveKeyByUser(ctx context.Context, userID uuid.UUID) (AdoKey, error) {
	row := q.db.QueryRow(ctx, getActiveKeyByUser, userID)
	var i AdoKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.DailyLimit,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getActiveKeyWithQuotaByUser = `-- name: GetActiveKeyWithQuotaByUser :one
SELECT k.id, k.key_prefix, k.created_at, k.last_used_at, k.reasoning_mode,
       COALESCE(u.daily_quota_override, k.daily_limit)::int4 AS daily_limit
FROM ado_keys k
JOIN users u ON u.id = k.user_id
WHERE k.user_id = $1 AND k.revoked_at IS NULL`

type GetActiveKeyWithQuotaByUserRow struct {
	ID            uuid.UUID
	KeyPrefix     string
	CreatedAt     pgtype.Timestamptz
	LastUsedAt    pgtype.Timestamptz
	ReasoningMode bool
	DailyLimit    int32
}

func (q *Queries) GetActiveKeyWithQuotaByUser(ctx context.Context, userID uuid.UUID) (GetActiveKeyWithQuotaByUserRow, error) {
	row := q.db.QueryRow(ctx, getActiveKeyWithQuotaByUser, userID)
	var i GetActiveKeyWithQuotaByUserRow
	err := row.Scan(
		&i.ID,
		&i.KeyPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ReasoningMode,
		&i.DailyLimit,
	)
	return i, err
}

const getUsageForToday = `-- name: GetUsageForToday :one
SELECT COALESCE(used, 0)::int4 AS used
FROM daily_usage
WHERE key_id = $1 AND day = CURRENT_DATE
`

func (q *Queries) GetUsageForToday(ctx context.Context, keyID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getUsageForToday, keyID)
	var used int32
	err := row.Scan(&used)
	return used, err
}

const getKeyUsageHistory = `-- name: GetKeyUsageHistory :many
SELECT day, COALESCE(used, 0)::int4 AS used
FROM daily_usage
WHERE key_id = $1
  AND day >= CURRENT_DATE - INTERVAL '29 days'
ORDER BY day ASC
`

type GetKeyUsageHistoryRow struct {
	Day  pgtype.Date
	Used int32
}

func (q *Queries) GetKeyUsageHistory(ctx context.Context, keyID uuid.UUID) ([]GetKeyUsageHistoryRow, error) {
	rows, err := q.db.Query(ctx, getKeyUsageHistory, keyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetKeyUsageHistoryRow
	for rows.Next() {
		var i GetKeyUsageHistoryRow
		if err := rows.Scan(&i.Day, &i.Used); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const revokeActiveKeyForUser = `-- name: RevokeActiveKeyForUser :exec
UPDATE ado_keys SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeActiveKeyForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeActiveKeyForUser, userID)
	return err
}

const setActiveKeyReasoningMode = `-- name: SetActiveKeyReasoningMode :exec
UPDATE ado_keys SET reasoning_mode = $2
WHERE user_id = $1 AND revoked_at IS NULL
`

type SetActiveKeyReasoningModeParams struct {
	UserID        uuid.UUID
	ReasoningMode bool
}

func (q *Queries) SetActiveKeyReasoningMode(ctx context.Context, arg SetActiveKeyReasoningModeParams) error {
	_, err := q.db.Exec(ctx, setActiveKeyReasoningMode, arg.UserID, arg.ReasoningMode)
	return err
}

const touchKeyLastUsed = `-- name: TouchKeyLastUsed :exec
UPDATE ado_keys SET last_used_at = now()
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '30 seconds')
`

func (q *Queries) TouchKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchKeyLastUsed, id)
	return err
}
