// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdoKey struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	KeyPrefix  string
	KeyHash    []byte
	DailyLimit int32
	RevokedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

type DailyUsage struct {
	KeyID uuid.UUID
	Day   pgtype.Date
	Used  int32
}

type EmailVerificationToken struct {
	TokenHash  []byte
	UserID     uuid.UUID
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
}

type ErrorLog struct {
	ID        int64
	Level     string
	Message   string
	Context   []byte
	CreatedAt pgtype.Timestamptz
}

type Provider struct {
	ID        uuid.UUID
	Name      string
	BaseUrl   string
	ApiKey    string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Session struct {
	ID         []byte
	UserID     uuid.UUID
	CsrfToken  []byte
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	UserAgent  *string
	Ip         *netip.Addr
}

type SystemSetting struct {
	Key   string
	Value string
}

type User struct {
	ID                 uuid.UUID
	Email              string
	EmailVerified      bool
	PasswordHash       *string
	GoogleSub          *string
	DisplayName        *string
	PhotoUrl           *string
	Banned             bool
	Role               string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DailyQuotaOverride *int32
	DiscordID          *string
}
