// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AdoKey struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	KeyPrefix  string
	KeyHash    []byte
	DailyLimit int32
	RevokedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

type DailyUsage struct {
	KeyID pgtype.UUID
	Day   pgtype.Date
	Used  int32
}

type EmailVerificationToken struct {
	TokenHash  []byte
	UserID     pgtype.UUID
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
}

type Session struct {
	ID         []byte
	UserID     pgtype.UUID
	CsrfToken  []byte
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	UserAgent  *string
	Ip         *netip.Addr
}

type User struct {
	ID            pgtype.UUID
	Email         string
	EmailVerified bool
	PasswordHash  *string
	GoogleSub     *string
	DisplayName   *string
	PhotoUrl      *string
	Banned        bool
	Role          string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}
