// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countProviders = `-- name: CountProviders :one
SELECT COUNT(*) FROM providers
`

func (q *Queries) CountProviders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProviders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (name, base_url, api_key, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, name, base_url, api_key, is_active, created_at, updated_at
`

type CreateProviderParams struct {
	Name     string
	BaseUrl  string
	ApiKey   string
	IsActive bool
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKey,
		arg.IsActive,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKey,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM providers WHERE id = $1
`

func (q *Queries) DeleteProvider(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProvider, id)
	return err
}

const getActiveProvider = `-- name: GetActiveProvider :one
SELECT id, name, base_url, api_key, is_active, created_at, updated_at FROM providers WHERE is_active = TRUE LIMIT 1
`

func (q *Queries) GetActiveProvider(ctx context.Context) (Provider, error) {
	row := q.db.QueryRow(ctx, getActiveProvider)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKey,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviders = `-- name: ListProviders :many
SELECT id, name, base_url, api_key, is_active, created_at, updated_at FROM providers ORDER BY created_at ASC
`

func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKey,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProviderActive = `-- name: SetProviderActive :exec
UPDATE providers SET is_active = (id = $1), updated_at = NOW()
`

func (q *Queries) SetProviderActive(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setProviderActive, id)
	return err
}

const updateProviderKey = `-- name: UpdateProviderKey :exec
UPDATE providers SET api_key = $2, updated_at = NOW() WHERE id = $1
`

type UpdateProviderKeyParams struct {
	ID     uuid.UUID
	ApiKey string
}

func (q *Queries) UpdateProviderKey(ctx context.Context, arg UpdateProviderKeyParams) error {
	_, err := q.db.Exec(ctx, updateProviderKey, arg.ID, arg.ApiKey)
	return err
}

const updateProviderMeta = `-- name: UpdateProviderMeta :one
UPDATE providers
SET name = $2, base_url = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, name, base_url, api_key, is_active, created_at, updated_at
`

type UpdateProviderMetaParams struct {
	ID      uuid.UUID
	Name    string
	BaseUrl string
}

func (q *Queries) UpdateProviderMeta(ctx context.Context, arg UpdateProviderMetaParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProviderMeta, arg.ID, arg.Name, arg.BaseUrl)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKey,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
