// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, csrf_token, expires_at, user_agent, ip)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, csrf_token, created_at, last_seen_at, expires_at, user_agent, ip
`

type CreateSessionParams struct {
	ID        []byte
	UserID    uuid.UUID
	CsrfToken []byte
	ExpiresAt pgtype.Timestamptz
	UserAgent *string
	Ip        *netip.Addr
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.CsrfToken,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, csrf_token, created_at, last_seen_at, expires_at, user_agent, ip FROM sessions WHERE id = $1 AND expires_at > now()
`

func (q *Queries) GetSession(ctx context.Context, id []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now()
WHERE id = $1 AND last_seen_at < now() - interval '30 seconds'
`

func (q *Queries) TouchSession(ctx context.Context, id []byte) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}
