// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const incrementUsage = `-- name: IncrementUsage :one
INSERT INTO daily_usage (key_id, day, used)
VALUES ($1, CURRENT_DATE, 1)
ON CONFLICT (key_id, day) DO UPDATE
  SET used = daily_usage.used + 1
  WHERE daily_usage.used < $2
RETURNING used
`

type IncrementUsageParams struct {
	KeyID      uuid.UUID
	DailyLimit int32
}

func (q *Queries) IncrementUsage(ctx context.Context, arg IncrementUsageParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementUsage, arg.KeyID, arg.DailyLimit)
	var used int32
	err := row.Scan(&used)
	return used, err
}
